apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
  labels:
    project: roboshop
    purpose: practice
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0423899ec932dedaa
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static-demo
  labels:
    project: roboshop
    purpose: practice
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  volumes:
    - name: nginx-html
      persistentVolumeClaim:
        claimName: ebs-static
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-static
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    purpose: practice
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
      nodePort: 30002
  