apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: roboshop
data:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: frontend
      tier: frontend
  template:
    metadata:
      labels:
        project: roboshop
        component: frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: pavithrakasukurthi/frontend:v1
          imagePullPolicy: Always
          envFrom:
            - ConfigMapRef:
                name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
