apiVersion: v1
kind: Pod
metadata: 
  name: error-test
  labels:
    purpose: error-test

spec:
  containers:
    - name: frontend
      image: nginx:gvcxgb # wrong image name to test imagepullbackoff
    - name: almalinux
      image: almalinux:9 # missed start command to test crashloopbackoff error