apiVersion: v1
kind: Service
metadata:
  name: nodeport-demo
spec:
  type: NodePort 
  selector:
    project: roboshop
    environment: stage
    component: frontend
  ports:
    protocol: TCP
    port: 80
    targetPort: 80