apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboshop
  labels:
    project: roboshop
    environment: stage
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels: 
      project: roboshop
      environment: stage
      component: frontend
  template:
    metadata:
      name: deployment-demo
      labels:
        project: roboshop
        environment: stage
        component: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
    name: frontend
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    environment: stage
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
