apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboshop
  labels:
    project: roboshop
    environment: stage
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels: 
      project: roboshop
      environment: stage
      component: frontend
  template:
    metadata:
      name: deployment-demo
      labels:
        project: roboshop
        environment: stage
        component: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
