apiVersion: v1
kind: Pod 
metadata:
  name: pod-aff
  labels:
    project: roboshop
    purpose: demo
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
        labelSelectors:
          - matchExpressions:
              - key: project
                operator: In 
                values: roboshop 
                  - 
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: Always
          
