apiVersion: v1
kind: Pod 
metadata:
  name: pod-aff
  labels:
    project: roboshop
    purpose: demo
spec:
  affinity:
    podAntiAffinity:
      topologyKey: topology.kubernetes.io/hostname
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
           matchExpressions:
              - key:
                operator:
                values:
                  - 
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: Always
          
