apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    component: redis
    tier: db
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      component: redis
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: db
    spec:
      containers:
        - name: redis
          image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: redis
    tier: db
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: 6379
